// =============================================================================
// GEMSTONE — Site Configuration
// =============================================================================

export const siteConfig = {
  name: "GEMSTONE",
  tagline: "WE RENDER THE UNSEEN.",
  description:
    "정제되지 않은 데이터 속에서 빛나는 인사이트를 세공하는 데이터 분석 크루",
  url: "https://gemstone-site.vercel.app",
};

// =============================================================================
// Navigation
// =============================================================================

export const navItems = [
  { label: "PARAMETERS", href: "#parameters" },
  { label: "ARCHIVE", href: "#archive" },
  { label: "INIT", href: "#init" },
  { label: "EXECUTE", href: "#execute" },
];

// =============================================================================
// Core Parameters — Club Introduction Data
// =============================================================================

export const coreParameters = [
  {
    id: "DEPENDENCY",
    label: "DEPENDENCY",
    value: "NONE",
    numericValue: 0,
    maxValue: 100,
    description:
      "사전 지식은 필요 없습니다. 열정이라는 변수만 있다면 시스템이 빌드합니다.",
  },
  {
    id: "LEARNING_CURVE",
    label: "LEARNING_CURVE",
    value: "OPTIMIZED",
    numericValue: 92,
    maxValue: 100,
    description:
      "실전 파이썬 분석 기법만 압축하여 누구나 데이터와 대화하게 만듭니다.",
  },
  {
    id: "TEAM_STATUS",
    label: "TEAM_STATUS",
    value: "RECRUITING",
    numericValue: 67,
    maxValue: 100,
    description:
      "데이터를 해체하고 재조립할 새로운 원석을 호출합니다.",
  },
];

// =============================================================================
// Data Archive — ML Project Showcase
// =============================================================================

export interface Project {
  id: string;
  field: string;
  title: string;
  titleKr: string;
  description: string;
  tech: string[];
  tags?: string[];
  status: "EXECUTED" | "IN_PROGRESS" | "ARCHIVED";
  accuracy?: string;
}

export const projects: Project[] = [
  {
    id: "GEM-001",
    field: "MARKETING",
    title: "Customer Churn Prediction",
    titleKr: "이탈 고객 예측 모델",
    description: "참여자: 권성현, 박성빈, 오지훈, 윤지수\n\n프로젝트 목표: 실시간 스트리밍 데이터를 기반으로 추천 알고리즘 고도화. 기존 시스템 대비 지연 시간을 최소화하고 사용자 경험을 개선했다.\n\n성과: 현업 적용 테스트 결과 비즈니스 지표 15% 상승 효과 입증. 시스템 파이프라인 자동화로 운영 비용을 대폭 절감했다.",
    tech: ["Python","Surprise","SparkML","Redis","FastAPI"],
    tags: ["ML","Classification"],
    status: "EXECUTED",
    accuracy: "84.7%",
  },
  {
    id: "GEM-002",
    field: "SPORTS",
    title: "Player Performance Analytics",
    titleKr: "KBO 선수 성적 예측",
    description: "참여자: 강태민, 오지훈, 손지호, 정다은, 최유진\n\n프로젝트 목표: 대규모 데이터를 분석하여 주요 지표를 예측하는 예측 모델 구축. 다양한 알고리즘을 비교 실험하고 최적 앙상블 전략을 설계했다.\n\n성과: 기존 대비 성능 지표 25% 개선, 실무 부서의 의사결정 속도 단축. 분석 결과를 바탕으로 최적화 전략을 도출하여 실제 서비스에 반영했다.",
    tech: ["Python","LightGBM","RandomForest","SHAP","Plotly"],
    tags: ["TimeSeries","DL"],
    status: "EXECUTED",
    accuracy: "97.1%",
  },
  {
    id: "GEM-003",
    field: "HEALTHCARE",
    title: "Medical Image Classification",
    titleKr: "흉부 X-ray 이미지 분류",
    description: "참여자: 최아영, 김민준, 박성빈, 최준서\n\n프로젝트 목표: 실시간 스트리밍 데이터를 기반으로 추천 알고리즘 고도화. 기존 시스템 대비 지연 시간을 최소화하고 사용자 경험을 개선했다.\n\n성과: 모델 정확도 90% 이상 달성. 인터랙티브 대시보드로 구현하여 비개발 직군도 쉽게 결과를 활용할 수 있도록 배포했다.",
    tech: ["Python","Surprise","SparkML","Redis","FastAPI"],
    tags: ["CV","DL","Transfer Learning"],
    status: "ARCHIVED",
    accuracy: "—",
  },
  {
    id: "GEM-004",
    field: "FINANCE",
    title: "Credit Risk Scoring",
    titleKr: "신용 리스크 스코어링",
    description: "참여자: 강현우, 이찬호, 서도현, 조아린, 엄지은\n\n프로젝트 목표: 대규모 데이터를 분석하여 주요 지표를 예측하는 예측 모델 구축. 다양한 알고리즘을 비교 실험하고 최적 앙상블 전략을 설계했다.\n\n성과: 모델 정확도 90% 이상 달성. 인터랙티브 대시보드로 구현하여 비개발 직군도 쉽게 결과를 활용할 수 있도록 배포했다.",
    tech: ["Python","PyTorch","ResNet-50","OpenCV","NumPy"],
    tags: ["ML","FinTech"],
    status: "EXECUTED",
    accuracy: "90.6%",
  },
  {
    id: "GEM-005",
    field: "E-COMMERCE",
    title: "Recommendation Engine",
    titleKr: "상품 추천 시스템",
    description: "참여자: 정다은, 강소희, 오지훈, 황준혁, 박지현\n\n프로젝트 목표: 비정형 데이터(이미지/텍스트)를 활용하여 자동 분류 및 탐지 시스템 구축. 최신 딥러닝 아키텍처와 전이 학습을 적용했다.\n\n성과: 모델 정확도 90% 이상 달성. 인터랙티브 대시보드로 구현하여 비개발 직군도 쉽게 결과를 활용할 수 있도록 배포했다.",
    tech: ["Python","TensorFlow","LSTM","Statsmodels","Seaborn"],
    tags: ["RecSys","ML"],
    status: "ARCHIVED",
    accuracy: "—",
  },
  {
    id: "GEM-006",
    field: "NLP",
    title: "Sentiment Analysis Dashboard",
    titleKr: "소셜 미디어 감성 분석",
    description: "참여자: 이준범, 윤지수, 오민재, 강태민\n\n프로젝트 목표: 시계열 분석을 통해 향후 트렌드 및 변화 패턴을 정량화하는 모델 개발. 외부 변수를 적극 활용하여 정확도를 높였다.\n\n성과: 기존 대비 성능 지표 25% 개선, 실무 부서의 의사결정 속도 단축. 분석 결과를 바탕으로 최적화 전략을 도출하여 실제 서비스에 반영했다.",
    tech: ["Python","Surprise","SparkML","Redis","FastAPI"],
    tags: ["NLP","DL","Sentiment"],
    status: "EXECUTED",
    accuracy: "85.5%",
  },
  {
    id: "GEM-007",
    field: "LOGISTICS",
    title: "Demand Forecasting System",
    titleKr: "물류 수요 예측 시스템",
    description: "참여자: 노준혁, 윤지수, 임채원, 박태양\n\n프로젝트 목표: 시계열 분석을 통해 향후 트렌드 및 변화 패턴을 정량화하는 모델 개발. 외부 변수를 적극 활용하여 정확도를 높였다.\n\n성과: 정확도를 획기적으로 향상시켜 타겟 마케팅 효율을 30% 증가시켰다. 이로 인해 사내 우수 프로젝트로 선정되어 전사 확대 적용되었다.",
    tech: ["Python","Prophet","XGBoost","Airflow","PostgreSQL"],
    tags: ["TimeSeries","MLOps"],
    status: "EXECUTED",
    accuracy: "93.4%",
  },
  {
    id: "GEM-008",
    field: "ENVIRONMENT",
    title: "Air Quality Prediction",
    titleKr: "대기질 예측 모델",
    description: "참여자: 김나연, 오민재, 정시우, 최유진, 이서연\n\n프로젝트 목표: 대규모 데이터를 분석하여 주요 지표를 예측하는 예측 모델 구축. 다양한 알고리즘을 비교 실험하고 최적 앙상블 전략을 설계했다.\n\n성과: 기존 대비 성능 지표 25% 개선, 실무 부서의 의사결정 속도 단축. 분석 결과를 바탕으로 최적화 전략을 도출하여 실제 서비스에 반영했다.",
    tech: ["Python","PyTorch","ResNet-50","OpenCV","NumPy"],
    tags: ["TimeSeries","DL","GIS"],
    status: "IN_PROGRESS",
    accuracy: "—",
  },
  {
    id: "GEM-009",
    field: "REAL ESTATE",
    title: "Property Price Prediction",
    titleKr: "부동산 가격 예측",
    description: "참여자: 장미래, 신예린, 한승우, 박성빈\n\n프로젝트 목표: 복잡한 피처 엔지니어링을 통해 이상 탐지 및 분류 모델 개발. 설명 가능한 AI(XAI)를 도입하여 의사결정 근거를 시각화했다.\n\n성과: 정확도를 획기적으로 향상시켜 타겟 마케팅 효율을 30% 증가시켰다. 이로 인해 사내 우수 프로젝트로 선정되어 전사 확대 적용되었다.",
    tech: ["Python","LightGBM","RandomForest","SHAP","Plotly"],
    tags: ["ML","GIS"],
    status: "EXECUTED",
    accuracy: "82.6%",
  },
  {
    id: "GEM-010",
    field: "CYBERSECURITY",
    title: "Network Intrusion Detection",
    titleKr: "네트워크 침입 탐지",
    description: "참여자: 김민준, 김나연, 한승우, 강현우\n\n프로젝트 목표: 대규모 데이터를 분석하여 주요 지표를 예측하는 예측 모델 구축. 다양한 알고리즘을 비교 실험하고 최적 앙상블 전략을 설계했다.\n\n성과: 기존 대비 성능 지표 25% 개선, 실무 부서의 의사결정 속도 단축. 분석 결과를 바탕으로 최적화 전략을 도출하여 실제 서비스에 반영했다.",
    tech: ["Python","GRU","TensorFlow","Pandas","Folium"],
    tags: ["Anomaly Detection","Security"],
    status: "ARCHIVED",
    accuracy: "—",
  },
  {
    id: "GEM-011",
    field: "RETAIL",
    title: "Store Sales Optimization",
    titleKr: "매장 매출 최적화 분석",
    description: "참여자: 임태양, 유하늘, 백하은, 김다인\n\n프로젝트 목표: 실시간 스트리밍 데이터를 기반으로 추천 알고리즘 고도화. 기존 시스템 대비 지연 시간을 최소화하고 사용자 경험을 개선했다.\n\n성과: 현업 적용 테스트 결과 비즈니스 지표 15% 상승 효과 입증. 시스템 파이프라인 자동화로 운영 비용을 대폭 절감했다.",
    tech: ["Python","PyTorch","ResNet-50","OpenCV","NumPy"],
    tags: ["Analytics","A/B Test"],
    status: "EXECUTED",
    accuracy: "89.6%",
  },
  {
    id: "GEM-012",
    field: "AUTONOMOUS",
    title: "Lane Detection System",
    titleKr: "자율주행 차선 인식",
    description: "참여자: 배수아, 박도현, 김민준, 황준혁, 윤지수\n\n프로젝트 목표: 비정형 데이터(이미지/텍스트)를 활용하여 자동 분류 및 탐지 시스템 구축. 최신 딥러닝 아키텍처와 전이 학습을 적용했다.\n\n성과: 기존 대비 성능 지표 25% 개선, 실무 부서의 의사결정 속도 단축. 분석 결과를 바탕으로 최적화 전략을 도출하여 실제 서비스에 반영했다.",
    tech: ["Python","XGBoost","Pandas","Scikit-learn","Matplotlib"],
    tags: ["CV","Autonomous","Segmentation"],
    status: "ARCHIVED",
    accuracy: "—",
  },
  {
    id: "GEM-013",
    field: "AGRICULTURE",
    title: "Crop Disease Detection",
    titleKr: "작물 병해충 탐지",
    description: "참여자: 강소희, 서지안, 임채원, 한승우, 엄지은\n\n프로젝트 목표: 실시간 스트리밍 데이터를 기반으로 추천 알고리즘 고도화. 기존 시스템 대비 지연 시간을 최소화하고 사용자 경험을 개선했다.\n\n성과: 현업 적용 테스트 결과 비즈니스 지표 15% 상승 효과 입증. 시스템 파이프라인 자동화로 운영 비용을 대폭 절감했다.",
    tech: ["Python","KoBERT","HuggingFace","Streamlit","MongoDB"],
    tags: ["CV","DL","AgriTech"],
    status: "EXECUTED",
    accuracy: "96.0%",
  },
  {
    id: "GEM-014",
    field: "EDUCATION",
    title: "Student Performance Prediction",
    titleKr: "학업 성취도 예측",
    description: "참여자: 이찬호, 유하늘, 신민철, 신예린, 고민준\n\n프로젝트 목표: 비정형 데이터(이미지/텍스트)를 활용하여 자동 분류 및 탐지 시스템 구축. 최신 딥러닝 아키텍처와 전이 학습을 적용했다.\n\n성과: 정확도를 획기적으로 향상시켜 타겟 마케팅 효율을 30% 증가시켰다. 이로 인해 사내 우수 프로젝트로 선정되어 전사 확대 적용되었다.",
    tech: ["Python","LightGBM","RandomForest","SHAP","Plotly"],
    tags: ["ML","Clustering","EdTech"],
    status: "EXECUTED",
    accuracy: "91.7%",
  },
  {
    id: "GEM-015",
    field: "ENERGY",
    title: "Smart Grid Load Forecasting",
    titleKr: "스마트 그리드 부하 예측",
    description: "참여자: 장미래, 백하은, 박태양, 박세은, 박지현\n\n프로젝트 목표: 실시간 스트리밍 데이터를 기반으로 추천 알고리즘 고도화. 기존 시스템 대비 지연 시간을 최소화하고 사용자 경험을 개선했다.\n\n성과: 기존 대비 성능 지표 25% 개선, 실무 부서의 의사결정 속도 단축. 분석 결과를 바탕으로 최적화 전략을 도출하여 실제 서비스에 반영했다.",
    tech: ["Python","Surprise","SparkML","Redis","FastAPI"],
    tags: ["TimeSeries","DL","Energy"],
    status: "EXECUTED",
    accuracy: "95.8%",
  },
  {
    id: "GEM-016",
    field: "FASHION",
    title: "Outfit Compatibility Scoring",
    titleKr: "패션 코디 호환성 분석",
    description: "참여자: 남동훈, 최준서, 백하은, 엄지은, 윤지수\n\n프로젝트 목표: 비정형 데이터(이미지/텍스트)를 활용하여 자동 분류 및 탐지 시스템 구축. 최신 딥러닝 아키텍처와 전이 학습을 적용했다.\n\n성과: 모델 정확도 90% 이상 달성. 인터랙티브 대시보드로 구현하여 비개발 직군도 쉽게 결과를 활용할 수 있도록 배포했다.",
    tech: ["Python","XGBoost","Pandas","Scikit-learn","Matplotlib"],
    tags: ["CV","DL","RecSys"],
    status: "EXECUTED",
    accuracy: "83.2%",
  },
  {
    id: "GEM-017",
    field: "SOCIAL SCIENCE",
    title: "Election Outcome Modeling",
    titleKr: "선거 결과 예측 모델",
    description: "참여자: 서도현, 김민준, 강태민, 임태양\n\n프로젝트 목표: 대규모 데이터를 분석하여 주요 지표를 예측하는 예측 모델 구축. 다양한 알고리즘을 비교 실험하고 최적 앙상블 전략을 설계했다.\n\n성과: 기존 대비 성능 지표 25% 개선, 실무 부서의 의사결정 속도 단축. 분석 결과를 바탕으로 최적화 전략을 도출하여 실제 서비스에 반영했다.",
    tech: ["Python","PyTorch","ResNet-50","OpenCV","NumPy"],
    tags: ["ML","Bayesian","NLP"],
    status: "ARCHIVED",
    accuracy: "—",
  },
  {
    id: "GEM-018",
    field: "GAMING",
    title: "Player Behavior Clustering",
    titleKr: "게임 플레이어 행동 분석",
    description: "참여자: 이찬호, 김나연, 배수아, 김다인\n\n프로젝트 목표: 복잡한 피처 엔지니어링을 통해 이상 탐지 및 분류 모델 개발. 설명 가능한 AI(XAI)를 도입하여 의사결정 근거를 시각화했다.\n\n성과: 오탐률을 기존 대비 절반으로 낮추고, 실시간 추론이 가능한 경량화 버전을 별도 제작하여 운영 환경에 성공적으로 배포했다.",
    tech: ["Python","XGBoost","Pandas","Scikit-learn","Matplotlib"],
    tags: ["Clustering","Analytics"],
    status: "EXECUTED",
    accuracy: "88.3%",
  },
  {
    id: "GEM-019",
    field: "TRANSPORTATION",
    title: "Traffic Flow Prediction",
    titleKr: "도심 교통량 예측",
    description: "참여자: 박도현, 전하린, 홍다빈, 문가을, 이소율\n\n프로젝트 목표: 대규모 데이터를 분석하여 주요 지표를 예측하는 예측 모델 구축. 다양한 알고리즘을 비교 실험하고 최적 앙상블 전략을 설계했다.\n\n성과: 현업 적용 테스트 결과 비즈니스 지표 15% 상승 효과 입증. 시스템 파이프라인 자동화로 운영 비용을 대폭 절감했다.",
    tech: ["Python","PyTorch","ResNet-50","OpenCV","NumPy"],
    tags: ["GNN","TimeSeries","GIS"],
    status: "IN_PROGRESS",
    accuracy: "—",
  },
  {
    id: "GEM-020",
    field: "MEDIA",
    title: "Video Thumbnail CTR Prediction",
    titleKr: "유튜브 썸네일 CTR 예측",
    description: "참여자: 류동현, 전하린, 박지현, 장미래\n\n프로젝트 목표: 실시간 스트리밍 데이터를 기반으로 추천 알고리즘 고도화. 기존 시스템 대비 지연 시간을 최소화하고 사용자 경험을 개선했다.\n\n성과: 정확도를 획기적으로 향상시켜 타겟 마케팅 효율을 30% 증가시켰다. 이로 인해 사내 우수 프로젝트로 선정되어 전사 확대 적용되었다.",
    tech: ["Python","Prophet","XGBoost","Airflow","PostgreSQL"],
    tags: ["Multimodal","NLP","CV"],
    status: "IN_PROGRESS",
    accuracy: "—",
  },
  {
    id: "GEM-021",
    field: "MANUFACTURING",
    title: "Defect Detection System",
    titleKr: "제조 공정 불량 탐지",
    description: "참여자: 이도준, 엄지은, 박지현, 유하늘\n\n프로젝트 목표: 비정형 데이터(이미지/텍스트)를 활용하여 자동 분류 및 탐지 시스템 구축. 최신 딥러닝 아키텍처와 전이 학습을 적용했다.\n\n성과: 모델 정확도 90% 이상 달성. 인터랙티브 대시보드로 구현하여 비개발 직군도 쉽게 결과를 활용할 수 있도록 배포했다.",
    tech: ["Python","PyTorch","ResNet-50","OpenCV","NumPy"],
    tags: ["CV","Anomaly Detection"],
    status: "EXECUTED",
    accuracy: "82.5%",
  },
  {
    id: "GEM-022",
    field: "ENTERTAINMENT",
    title: "Content Success Prediction",
    titleKr: "콘텐츠 흥행 예측",
    description: "참여자: 최준서, 이소율, 권성현, 엄지은\n\n프로젝트 목표: 대규모 데이터를 분석하여 주요 지표를 예측하는 예측 모델 구축. 다양한 알고리즘을 비교 실험하고 최적 앙상블 전략을 설계했다.\n\n성과: 현업 적용 테스트 결과 비즈니스 지표 15% 상승 효과 입증. 시스템 파이프라인 자동화로 운영 비용을 대폭 절감했다.",
    tech: ["Python","PyTorch","ResNet-50","OpenCV","NumPy"],
    tags: ["RecSys","NLP"],
    status: "IN_PROGRESS",
    accuracy: "—",
  },
  {
    id: "GEM-023",
    field: "MARKETING",
    title: "Customer Churn Prediction",
    titleKr: "이탈 고객 예측 모델",
    description: "참여자: 노준혁, 이찬호, 박태양, 한승우, 배수아\n\n프로젝트 목표: 시계열 분석을 통해 향후 트렌드 및 변화 패턴을 정량화하는 모델 개발. 외부 변수를 적극 활용하여 정확도를 높였다.\n\n성과: 정확도를 획기적으로 향상시켜 타겟 마케팅 효율을 30% 증가시켰다. 이로 인해 사내 우수 프로젝트로 선정되어 전사 확대 적용되었다.",
    tech: ["Python","CatBoost","GeoPandas","Scikit-learn","Dash"],
    tags: ["ML","Classification"],
    status: "EXECUTED",
    accuracy: "93.0%",
  },
  {
    id: "GEM-024",
    field: "SPORTS",
    title: "Player Performance Analytics",
    titleKr: "KBO 선수 성적 예측",
    description: "참여자: 김나연, 남동훈, 손지호, 최아영\n\n프로젝트 목표: 비정형 데이터(이미지/텍스트)를 활용하여 자동 분류 및 탐지 시스템 구축. 최신 딥러닝 아키텍처와 전이 학습을 적용했다.\n\n성과: 현업 적용 테스트 결과 비즈니스 지표 15% 상승 효과 입증. 시스템 파이프라인 자동화로 운영 비용을 대폭 절감했다.",
    tech: ["Python","Surprise","SparkML","Redis","FastAPI"],
    tags: ["TimeSeries","DL"],
    status: "EXECUTED",
    accuracy: "96.0%",
  },
  {
    id: "GEM-025",
    field: "HEALTHCARE",
    title: "Medical Image Classification",
    titleKr: "흉부 X-ray 이미지 분류",
    description: "참여자: 최유진, 노준혁, 장미래, 남동훈, 류동현\n\n프로젝트 목표: 복잡한 피처 엔지니어링을 통해 이상 탐지 및 분류 모델 개발. 설명 가능한 AI(XAI)를 도입하여 의사결정 근거를 시각화했다.\n\n성과: 오탐률을 기존 대비 절반으로 낮추고, 실시간 추론이 가능한 경량화 버전을 별도 제작하여 운영 환경에 성공적으로 배포했다.",
    tech: ["Python","GRU","TensorFlow","Pandas","Folium"],
    tags: ["CV","DL","Transfer Learning"],
    status: "EXECUTED",
    accuracy: "90.7%",
  },
  {
    id: "GEM-026",
    field: "FINANCE",
    title: "Credit Risk Scoring",
    titleKr: "신용 리스크 스코어링",
    description: "참여자: 강소희, 서지안, 박지현, 배수아, 엄지은\n\n프로젝트 목표: 대규모 데이터를 분석하여 주요 지표를 예측하는 예측 모델 구축. 다양한 알고리즘을 비교 실험하고 최적 앙상블 전략을 설계했다.\n\n성과: 오탐률을 기존 대비 절반으로 낮추고, 실시간 추론이 가능한 경량화 버전을 별도 제작하여 운영 환경에 성공적으로 배포했다.",
    tech: ["Python","KoBERT","HuggingFace","Streamlit","MongoDB"],
    tags: ["ML","FinTech"],
    status: "EXECUTED",
    accuracy: "83.1%",
  },
  {
    id: "GEM-027",
    field: "E-COMMERCE",
    title: "Recommendation Engine",
    titleKr: "상품 추천 시스템",
    description: "참여자: 박성빈, 한승우, 강소희, 박태양, 김나연\n\n프로젝트 목표: 시계열 분석을 통해 향후 트렌드 및 변화 패턴을 정량화하는 모델 개발. 외부 변수를 적극 활용하여 정확도를 높였다.\n\n성과: 모델 정확도 90% 이상 달성. 인터랙티브 대시보드로 구현하여 비개발 직군도 쉽게 결과를 활용할 수 있도록 배포했다.",
    tech: ["Python","Prophet","XGBoost","Airflow","PostgreSQL"],
    tags: ["RecSys","ML"],
    status: "EXECUTED",
    accuracy: "84.3%",
  },
  {
    id: "GEM-028",
    field: "NLP",
    title: "Sentiment Analysis Dashboard",
    titleKr: "소셜 미디어 감성 분석",
    description: "참여자: 박태양, 서도현, 최아영, 윤지수\n\n프로젝트 목표: 시계열 분석을 통해 향후 트렌드 및 변화 패턴을 정량화하는 모델 개발. 외부 변수를 적극 활용하여 정확도를 높였다.\n\n성과: 오탐률을 기존 대비 절반으로 낮추고, 실시간 추론이 가능한 경량화 버전을 별도 제작하여 운영 환경에 성공적으로 배포했다.",
    tech: ["Python","XGBoost","Pandas","Scikit-learn","Matplotlib"],
    tags: ["NLP","DL","Sentiment"],
    status: "EXECUTED",
    accuracy: "92.1%",
  },
  {
    id: "GEM-029",
    field: "LOGISTICS",
    title: "Demand Forecasting System",
    titleKr: "물류 수요 예측 시스템",
    description: "참여자: 임채원, 유하늘, 배수아, 권성현, 신민철\n\n프로젝트 목표: 시계열 분석을 통해 향후 트렌드 및 변화 패턴을 정량화하는 모델 개발. 외부 변수를 적극 활용하여 정확도를 높였다.\n\n성과: 오탐률을 기존 대비 절반으로 낮추고, 실시간 추론이 가능한 경량화 버전을 별도 제작하여 운영 환경에 성공적으로 배포했다.",
    tech: ["Python","Prophet","XGBoost","Airflow","PostgreSQL"],
    tags: ["TimeSeries","MLOps"],
    status: "EXECUTED",
    accuracy: "89.2%",
  },
  {
    id: "GEM-030",
    field: "ENVIRONMENT",
    title: "Air Quality Prediction",
    titleKr: "대기질 예측 모델",
    description: "참여자: 유하늘, 남동훈, 한채린, 신예린\n\n프로젝트 목표: 비정형 데이터(이미지/텍스트)를 활용하여 자동 분류 및 탐지 시스템 구축. 최신 딥러닝 아키텍처와 전이 학습을 적용했다.\n\n성과: 기존 대비 성능 지표 25% 개선, 실무 부서의 의사결정 속도 단축. 분석 결과를 바탕으로 최적화 전략을 도출하여 실제 서비스에 반영했다.",
    tech: ["Python","CatBoost","GeoPandas","Scikit-learn","Dash"],
    tags: ["TimeSeries","DL","GIS"],
    status: "EXECUTED",
    accuracy: "90.6%",
  },
  {
    id: "GEM-031",
    field: "REAL ESTATE",
    title: "Property Price Prediction",
    titleKr: "부동산 가격 예측",
    description: "참여자: 오지훈, 서도현, 윤지수, 손지호, 유하늘\n\n프로젝트 목표: 대규모 데이터를 분석하여 주요 지표를 예측하는 예측 모델 구축. 다양한 알고리즘을 비교 실험하고 최적 앙상블 전략을 설계했다.\n\n성과: 기존 대비 성능 지표 25% 개선, 실무 부서의 의사결정 속도 단축. 분석 결과를 바탕으로 최적화 전략을 도출하여 실제 서비스에 반영했다.",
    tech: ["Python","Surprise","SparkML","Redis","FastAPI"],
    tags: ["ML","GIS"],
    status: "IN_PROGRESS",
    accuracy: "—",
  },
  {
    id: "GEM-032",
    field: "CYBERSECURITY",
    title: "Network Intrusion Detection",
    titleKr: "네트워크 침입 탐지",
    description: "참여자: 권성현, 김도연, 백하은, 서도현, 최유진\n\n프로젝트 목표: 대규모 데이터를 분석하여 주요 지표를 예측하는 예측 모델 구축. 다양한 알고리즘을 비교 실험하고 최적 앙상블 전략을 설계했다.\n\n성과: 오탐률을 기존 대비 절반으로 낮추고, 실시간 추론이 가능한 경량화 버전을 별도 제작하여 운영 환경에 성공적으로 배포했다.",
    tech: ["Python","LightGBM","RandomForest","SHAP","Plotly"],
    tags: ["Anomaly Detection","Security"],
    status: "EXECUTED",
    accuracy: "86.7%",
  },
  {
    id: "GEM-033",
    field: "RETAIL",
    title: "Store Sales Optimization",
    titleKr: "매장 매출 최적화 분석",
    description: "참여자: 박태양, 신민철, 박성빈, 엄지은\n\n프로젝트 목표: 시계열 분석을 통해 향후 트렌드 및 변화 패턴을 정량화하는 모델 개발. 외부 변수를 적극 활용하여 정확도를 높였다.\n\n성과: 오탐률을 기존 대비 절반으로 낮추고, 실시간 추론이 가능한 경량화 버전을 별도 제작하여 운영 환경에 성공적으로 배포했다.",
    tech: ["Python","KoBERT","HuggingFace","Streamlit","MongoDB"],
    tags: ["Analytics","A/B Test"],
    status: "EXECUTED",
    accuracy: "93.7%",
  },
  {
    id: "GEM-034",
    field: "AUTONOMOUS",
    title: "Lane Detection System",
    titleKr: "자율주행 차선 인식",
    description: "참여자: 김나연, 최준서, 엄지은, 류동현, 황준혁\n\n프로젝트 목표: 시계열 분석을 통해 향후 트렌드 및 변화 패턴을 정량화하는 모델 개발. 외부 변수를 적극 활용하여 정확도를 높였다.\n\n성과: 모델 정확도 90% 이상 달성. 인터랙티브 대시보드로 구현하여 비개발 직군도 쉽게 결과를 활용할 수 있도록 배포했다.",
    tech: ["Python","Prophet","XGBoost","Airflow","PostgreSQL"],
    tags: ["CV","Autonomous","Segmentation"],
    status: "EXECUTED",
    accuracy: "96.7%",
  },
  {
    id: "GEM-035",
    field: "AGRICULTURE",
    title: "Crop Disease Detection",
    titleKr: "작물 병해충 탐지",
    description: "참여자: 임채원, 전하린, 강소희, 노준혁, 남동훈\n\n프로젝트 목표: 시계열 분석을 통해 향후 트렌드 및 변화 패턴을 정량화하는 모델 개발. 외부 변수를 적극 활용하여 정확도를 높였다.\n\n성과: 기존 대비 성능 지표 25% 개선, 실무 부서의 의사결정 속도 단축. 분석 결과를 바탕으로 최적화 전략을 도출하여 실제 서비스에 반영했다.",
    tech: ["Python","CatBoost","GeoPandas","Scikit-learn","Dash"],
    tags: ["CV","DL","AgriTech"],
    status: "EXECUTED",
    accuracy: "81.6%",
  },
  {
    id: "GEM-036",
    field: "EDUCATION",
    title: "Student Performance Prediction",
    titleKr: "학업 성취도 예측",
    description: "참여자: 한채린, 박지현, 유채원, 임태양, 이소율\n\n프로젝트 목표: 비정형 데이터(이미지/텍스트)를 활용하여 자동 분류 및 탐지 시스템 구축. 최신 딥러닝 아키텍처와 전이 학습을 적용했다.\n\n성과: 현업 적용 테스트 결과 비즈니스 지표 15% 상승 효과 입증. 시스템 파이프라인 자동화로 운영 비용을 대폭 절감했다.",
    tech: ["Python","TensorFlow","LSTM","Statsmodels","Seaborn"],
    tags: ["ML","Clustering","EdTech"],
    status: "EXECUTED",
    accuracy: "81.5%",
  },
  {
    id: "GEM-037",
    field: "ENERGY",
    title: "Smart Grid Load Forecasting",
    titleKr: "스마트 그리드 부하 예측",
    description: "참여자: 노준혁, 박도현, 박세은, 장미래\n\n프로젝트 목표: 시계열 분석을 통해 향후 트렌드 및 변화 패턴을 정량화하는 모델 개발. 외부 변수를 적극 활용하여 정확도를 높였다.\n\n성과: 정확도를 획기적으로 향상시켜 타겟 마케팅 효율을 30% 증가시켰다. 이로 인해 사내 우수 프로젝트로 선정되어 전사 확대 적용되었다.",
    tech: ["Python","TensorFlow","LSTM","Statsmodels","Seaborn"],
    tags: ["TimeSeries","DL","Energy"],
    status: "ARCHIVED",
    accuracy: "—",
  },
  {
    id: "GEM-038",
    field: "FASHION",
    title: "Outfit Compatibility Scoring",
    titleKr: "패션 코디 호환성 분석",
    description: "참여자: 김민준, 정다은, 윤지수, 문정호\n\n프로젝트 목표: 대규모 데이터를 분석하여 주요 지표를 예측하는 예측 모델 구축. 다양한 알고리즘을 비교 실험하고 최적 앙상블 전략을 설계했다.\n\n성과: 모델 정확도 90% 이상 달성. 인터랙티브 대시보드로 구현하여 비개발 직군도 쉽게 결과를 활용할 수 있도록 배포했다.",
    tech: ["Python","KoBERT","HuggingFace","Streamlit","MongoDB"],
    tags: ["CV","DL","RecSys"],
    status: "EXECUTED",
    accuracy: "95.7%",
  },
  {
    id: "GEM-039",
    field: "SOCIAL SCIENCE",
    title: "Election Outcome Modeling",
    titleKr: "선거 결과 예측 모델",
    description: "참여자: 장미래, 유채원, 유하늘, 정시우, 최서준\n\n프로젝트 목표: 실시간 스트리밍 데이터를 기반으로 추천 알고리즘 고도화. 기존 시스템 대비 지연 시간을 최소화하고 사용자 경험을 개선했다.\n\n성과: 기존 대비 성능 지표 25% 개선, 실무 부서의 의사결정 속도 단축. 분석 결과를 바탕으로 최적화 전략을 도출하여 실제 서비스에 반영했다.",
    tech: ["Python","PyTorch","ResNet-50","OpenCV","NumPy"],
    tags: ["ML","Bayesian","NLP"],
    status: "EXECUTED",
    accuracy: "97.1%",
  },
  {
    id: "GEM-040",
    field: "GAMING",
    title: "Player Behavior Clustering",
    titleKr: "게임 플레이어 행동 분석",
    description: "참여자: 류동현, 김하은, 배수아, 강소희\n\n프로젝트 목표: 대규모 데이터를 분석하여 주요 지표를 예측하는 예측 모델 구축. 다양한 알고리즘을 비교 실험하고 최적 앙상블 전략을 설계했다.\n\n성과: 현업 적용 테스트 결과 비즈니스 지표 15% 상승 효과 입증. 시스템 파이프라인 자동화로 운영 비용을 대폭 절감했다.",
    tech: ["Python","GRU","TensorFlow","Pandas","Folium"],
    tags: ["Clustering","Analytics"],
    status: "EXECUTED",
    accuracy: "92.5%",
  },
  {
    id: "GEM-041",
    field: "TRANSPORTATION",
    title: "Traffic Flow Prediction",
    titleKr: "도심 교통량 예측",
    description: "참여자: 손지호, 이찬호, 장미래, 한채린\n\n프로젝트 목표: 시계열 분석을 통해 향후 트렌드 및 변화 패턴을 정량화하는 모델 개발. 외부 변수를 적극 활용하여 정확도를 높였다.\n\n성과: 모델 정확도 90% 이상 달성. 인터랙티브 대시보드로 구현하여 비개발 직군도 쉽게 결과를 활용할 수 있도록 배포했다.",
    tech: ["Python","PyTorch","ResNet-50","OpenCV","NumPy"],
    tags: ["GNN","TimeSeries","GIS"],
    status: "EXECUTED",
    accuracy: "82.5%",
  },
  {
    id: "GEM-042",
    field: "MEDIA",
    title: "Video Thumbnail CTR Prediction",
    titleKr: "유튜브 썸네일 CTR 예측",
    description: "참여자: 박세은, 황준혁, 최유진, 박도현\n\n프로젝트 목표: 비정형 데이터(이미지/텍스트)를 활용하여 자동 분류 및 탐지 시스템 구축. 최신 딥러닝 아키텍처와 전이 학습을 적용했다.\n\n성과: 정확도를 획기적으로 향상시켜 타겟 마케팅 효율을 30% 증가시켰다. 이로 인해 사내 우수 프로젝트로 선정되어 전사 확대 적용되었다.",
    tech: ["Python","XGBoost","Pandas","Scikit-learn","Matplotlib"],
    tags: ["Multimodal","NLP","CV"],
    status: "IN_PROGRESS",
    accuracy: "—",
  },
  {
    id: "GEM-043",
    field: "MANUFACTURING",
    title: "Defect Detection System",
    titleKr: "제조 공정 불량 탐지",
    description: "참여자: 조아린, 윤지수, 박지현, 최유진\n\n프로젝트 목표: 대규모 데이터를 분석하여 주요 지표를 예측하는 예측 모델 구축. 다양한 알고리즘을 비교 실험하고 최적 앙상블 전략을 설계했다.\n\n성과: 오탐률을 기존 대비 절반으로 낮추고, 실시간 추론이 가능한 경량화 버전을 별도 제작하여 운영 환경에 성공적으로 배포했다.",
    tech: ["Python","Prophet","XGBoost","Airflow","PostgreSQL"],
    tags: ["CV","Anomaly Detection"],
    status: "EXECUTED",
    accuracy: "89.0%",
  },
  {
    id: "GEM-044",
    field: "ENTERTAINMENT",
    title: "Content Success Prediction",
    titleKr: "콘텐츠 흥행 예측",
    description: "참여자: 오민재, 강태민, 윤지수, 한채린, 박태양\n\n프로젝트 목표: 시계열 분석을 통해 향후 트렌드 및 변화 패턴을 정량화하는 모델 개발. 외부 변수를 적극 활용하여 정확도를 높였다.\n\n성과: 정확도를 획기적으로 향상시켜 타겟 마케팅 효율을 30% 증가시켰다. 이로 인해 사내 우수 프로젝트로 선정되어 전사 확대 적용되었다.",
    tech: ["Python","Surprise","SparkML","Redis","FastAPI"],
    tags: ["RecSys","NLP"],
    status: "ARCHIVED",
    accuracy: "—",
  },
  {
    id: "GEM-045",
    field: "MARKETING",
    title: "Customer Churn Prediction",
    titleKr: "이탈 고객 예측 모델",
    description: "참여자: 박지현, 최아영, 최서준, 이서연, 박도현\n\n프로젝트 목표: 시계열 분석을 통해 향후 트렌드 및 변화 패턴을 정량화하는 모델 개발. 외부 변수를 적극 활용하여 정확도를 높였다.\n\n성과: 모델 정확도 90% 이상 달성. 인터랙티브 대시보드로 구현하여 비개발 직군도 쉽게 결과를 활용할 수 있도록 배포했다.",
    tech: ["Python","CatBoost","GeoPandas","Scikit-learn","Dash"],
    tags: ["ML","Classification"],
    status: "EXECUTED",
    accuracy: "85.1%",
  },
  {
    id: "GEM-046",
    field: "SPORTS",
    title: "Player Performance Analytics",
    titleKr: "KBO 선수 성적 예측",
    description: "참여자: 한채린, 고민준, 노준혁, 남동훈\n\n프로젝트 목표: 실시간 스트리밍 데이터를 기반으로 추천 알고리즘 고도화. 기존 시스템 대비 지연 시간을 최소화하고 사용자 경험을 개선했다.\n\n성과: 기존 대비 성능 지표 25% 개선, 실무 부서의 의사결정 속도 단축. 분석 결과를 바탕으로 최적화 전략을 도출하여 실제 서비스에 반영했다.",
    tech: ["Python","KoBERT","HuggingFace","Streamlit","MongoDB"],
    tags: ["TimeSeries","DL"],
    status: "EXECUTED",
    accuracy: "80.9%",
  },
  {
    id: "GEM-047",
    field: "HEALTHCARE",
    title: "Medical Image Classification",
    titleKr: "흉부 X-ray 이미지 분류",
    description: "참여자: 한승우, 최아영, 유하늘, 김도연, 강태민\n\n프로젝트 목표: 시계열 분석을 통해 향후 트렌드 및 변화 패턴을 정량화하는 모델 개발. 외부 변수를 적극 활용하여 정확도를 높였다.\n\n성과: 현업 적용 테스트 결과 비즈니스 지표 15% 상승 효과 입증. 시스템 파이프라인 자동화로 운영 비용을 대폭 절감했다.",
    tech: ["Python","CatBoost","GeoPandas","Scikit-learn","Dash"],
    tags: ["CV","DL","Transfer Learning"],
    status: "EXECUTED",
    accuracy: "90.0%",
  }
];

// =============================================================================
// Curriculum Steps
// =============================================================================

export const curriculumSteps = [
  { 
    step: 1, 
    title: "🔰 초급반: 기초 다지기", 
    description: "• 환경 세팅: 파이썬·주피터 설치/실행\n• 파이썬 기본 문법, 자료구조, 간단한 크롤링\n• Pandas를 활용한 데이터 맛보기" 
  },
  { 
    step: 2, 
    title: "🚀 중급반: 분석 & 모델링", 
    description: "• NumPy·Pandas 심화, EDA 시각화\n• 데이터 전처리, Feature Engineering\n• 회귀/분류 모델(선형·로지스틱·랜덤포레스트) 실습" 
  },
  { 
    step: 3, 
    title: "🏆 공모전반: 실전 프로젝트", 
    description: "• 문제 정의 → 가설 수립 → 데이터 수집/모델링 → 결과 분석\n• Kaggle·국내 데이터 대회 대비 스터디\n• 팀 또는 개인 포트폴리오 완성" 
  },
];

// =============================================================================
// External Links
// =============================================================================

export const links = {
  applyForm: "https://forms.gle/PMs8zMKMdKVJwCfC6",
};
