// =============================================================================
// Query-data — Site Configuration
// =============================================================================

export const siteConfig = {
  name: "Query-data",
  tagline: "Ask the right questions.",
  description:
    "데이터에 질문하고, 인사이트로 답하는 데이터 분석 크루",
  url: "https://gemstone-site.vercel.app",
};

// =============================================================================
// Navigation
// =============================================================================

export const navItems = [
  { label: "About", href: "#parameters" },
  { label: "Archive", href: "#archive" },
  { label: "Curriculum", href: "#init" },
  { label: "Join", href: "#execute" },
];

// =============================================================================
// Core Parameters — Club Introduction Data
// =============================================================================

export const coreParameters = [
  {
    id: "DEPENDENCY",
    label: "사전 지식",
    value: "NONE",
    numericValue: 0,
    maxValue: 100,
    description:
      "사전 지식은 필요 없습니다. 열정만 있다면 누구든 시작할 수 있습니다.",
  },
  {
    id: "LEARNING_CURVE",
    label: "학습 효율",
    value: "OPTIMIZED",
    numericValue: 92,
    maxValue: 100,
    description:
      "실전 파이썬 분석 기법을 압축하여 누구나 데이터와 대화할 수 있게 됩니다.",
  },
  {
    id: "TEAM_STATUS",
    label: "모집 현황",
    value: "RECRUITING",
    numericValue: 67,
    maxValue: 100,
    description:
      "데이터에 올바른 질문을 던질 새로운 동료를 찾고 있습니다.",
  },
];

// =============================================================================
// Data Archive — ML Project Showcase
// =============================================================================

export interface Project {
  id: string;
  field: string;
  title: string;
  titleKr: string;
  description: string;
  tech: string[];
  tags?: string[];
  status: "EXECUTED" | "IN_PROGRESS" | "ARCHIVED";
  accuracy?: string;
}

export const projects: Project[] = [
  {
    id: "QD-001",
    field: "FINTECH",
    title: "Fraud Ring Network Mapping",
    titleKr: "금융 사기 조직 네트워크 시각화",
    description: "참여자: 강서윤, 고예담, 김가온\n\n프로젝트 목표: 카드 결제 트랜잭션 그래프에서 공모 사기 조직의 연결 패턴을 탐지하고, 커뮤니티 탐지 알고리즘으로 의심 클러스터를 자동 분류.\n\n성과: 기존 규칙 기반 시스템 대비 미탐지 사기 건수를 62% 감소시키고, 그래프 신경망(GNN)을 활용한 실시간 경보 파이프라인을 구축.",
    tech: ["Python", "DGL", "Neo4j", "FastAPI"],
    tags: ["Graph ML", "Fraud Detection"],
    status: "EXECUTED",
    accuracy: "93.7%",
  },
  {
    id: "QD-002",
    field: "MOBILITY",
    title: "EV Charging Demand Heatmap",
    titleKr: "전기차 충전 수요 히트맵 예측",
    description: "참여자: 권도하, 김나율, 김다현, 류다온\n\n프로젝트 목표: 도심 전기차 등록 현황, 교통량, 날씨 데이터를 결합하여 시간대·지역별 충전 수요를 예측하는 공간 분석 모델 개발.\n\n성과: 500m 격자 단위 수요 예측 정확도 91.4%를 달성하여 신규 충전소 입지 선정 의사결정 도구로 활용 가능성 입증.",
    tech: ["Python", "GeoPandas", "LightGBM", "Folium"],
    tags: ["Spatial Analysis", "EV"],
    status: "EXECUTED",
    accuracy: "91.4%",
  },
  {
    id: "QD-003",
    field: "BIOMEDICAL",
    title: "Retinal OCT Layer Segmentation",
    titleKr: "망막 OCT 영상 레이어 자동 분할",
    description: "참여자: 김민서, 김서준, 김수아\n\n프로젝트 목표: 안과 진단용 OCT 스캔 영상에서 10개 망막 층을 픽셀 단위로 자동 분할하는 U-Net 기반 세그멘테이션 모델 설계.\n\n성과: Dice 계수 0.94를 달성하여 전문의 수동 측정 대비 소요 시간을 95% 단축, 녹내장 조기 진단 보조 시스템으로 임상 파일럿 진행.",
    tech: ["Python", "PyTorch", "Monai", "OpenCV"],
    tags: ["Medical Imaging", "Segmentation"],
    status: "EXECUTED",
    accuracy: "94.0%",
  },
  {
    id: "QD-004",
    field: "RETAIL",
    title: "Dynamic Markdown Optimizer",
    titleKr: "소매 할인율 동적 최적화 엔진",
    description: "참여자: 김시현, 김연우, 김유나, 김은채\n\n프로젝트 목표: POS 매출 데이터와 재고 회전율을 분석하여 SKU별 최적 할인 시점 및 할인폭을 실시간으로 산출하는 가격 최적화 모델.\n\n성과: 시뮬레이션 결과 기존 정률 할인 대비 마진 손실을 23% 줄이면서도 재고 소진 속도를 18% 개선하는 효과를 확인.",
    tech: ["Python", "Optuna", "XGBoost", "Dash"],
    tags: ["Pricing", "Optimization"],
    status: "EXECUTED",
    accuracy: "87.2%",
  },
  {
    id: "QD-005",
    field: "CLIMATE",
    title: "Urban Heat Island Predictor",
    titleKr: "도시 열섬 현상 시공간 예측",
    description: "참여자: 김지안, 김지호, 김채원\n\n프로젝트 목표: Landsat 위성 열적외선 영상과 도시 피복 데이터를 융합하여 폭염 시기 구 단위 지표면 온도를 72시간 전에 예측.\n\n성과: MAE 1.2°C 이내의 예측 정밀도를 확보하여 자치구 폭염 대응 계획 수립 지원 도구로 활용.",
    tech: ["Python", "Rasterio", "TensorFlow", "QGIS"],
    tags: ["Climate", "Remote Sensing"],
    status: "EXECUTED",
    accuracy: "89.5%",
  },
  {
    id: "QD-006",
    field: "SOCIAL",
    title: "Youth Mental Health Signal Mining",
    titleKr: "청소년 정신건강 위험 신호 탐색",
    description: "참여자: 김하람, 나윤서, 류서하\n\n프로젝트 목표: 익명화된 온라인 커뮤니티 텍스트에서 우울, 불안, 자해 관련 언어 패턴을 탐지하여 조기 개입이 필요한 위험 신호를 분류.\n\n성과: 민감한 텍스트 분류에서 F1-Score 0.88을 달성하고, 상담 기관 연계를 위한 실시간 대시보드 프로토타입 제작.",
    tech: ["Python", "KoBERT", "Streamlit", "MongoDB"],
    tags: ["NLP", "Social Good"],
    status: "EXECUTED",
    accuracy: "88.0%",
  },
  {
    id: "QD-007",
    field: "MEDIA",
    title: "Podcast Listener Churn Forecast",
    titleKr: "팟캐스트 청취자 이탈 예측 모델",
    description: "참여자: 문정우, 박가영, 박건후, 박다율\n\n프로젝트 목표: 에피소드 완청률, 구독 기간, 재생 패턴 시계열 데이터를 분석하여 향후 2주 내 구독 해지 가능성이 높은 청취자를 식별.\n\n성과: 이탈 예측 Recall 91.3%를 달성하여 맞춤형 콘텐츠 추천 및 리텐션 캠페인 자동 발동 시스템과 연동.",
    tech: ["Python", "CatBoost", "Pandas", "Airflow"],
    tags: ["Media", "Churn"],
    status: "EXECUTED",
    accuracy: "91.3%",
  },
  {
    id: "QD-008",
    field: "AGRITECH",
    title: "Soil Nutrient Spectral Analysis",
    titleKr: "토양 양분 분광 분석 자동화",
    description: "참여자: 박서진, 박소율, 박시연\n\n프로젝트 목표: 근적외선(NIR) 분광 센서 데이터를 활용하여 질소·인·칼륨 함량을 실험실 분석 없이 현장에서 즉시 추정하는 모델 구축.\n\n성과: 기존 습식 화학 분석 대비 비용을 90% 절감하면서도 R² 0.91의 높은 예측력을 확보하여 스마트팜 토양 관리 시스템에 탑재.",
    tech: ["Python", "Scikit-Learn", "SciPy", "Streamlit"],
    tags: ["Agriculture", "Spectroscopy"],
    status: "EXECUTED",
    accuracy: "91.0%",
  },
  {
    id: "QD-009",
    field: "EDTECH",
    title: "Adaptive Quiz Difficulty Engine",
    titleKr: "적응형 퀴즈 난이도 조절 엔진",
    description: "참여자: 박유빈, 박은서, 박지윤, 배소은\n\n프로젝트 목표: 학습자의 문제 풀이 이력과 반응 시간을 기반으로 IRT(문항반응이론) 모델을 적용하여 개인 능력치에 맞는 다음 문항 난이도를 실시간 추천.\n\n성과: 학습 효율 지표(단위 시간당 정답률 향상)가 고정 난이도 대비 34% 개선됨을 A/B 테스트로 검증.",
    tech: ["Python", "PyTorch", "FastAPI", "PostgreSQL"],
    tags: ["EdTech", "Adaptive Learning"],
    status: "EXECUTED",
    accuracy: "86.8%",
  },
  {
    id: "QD-010",
    field: "SECURITY",
    title: "Encrypted Traffic Classifier",
    titleKr: "암호화 네트워크 트래픽 분류기",
    description: "참여자: 백서윤, 서예림, 서지원\n\n프로젝트 목표: TLS 암호화된 네트워크 패킷의 메타데이터(패킷 크기 분포, 간격 등)만으로 애플리케이션 유형을 판별하는 딥러닝 분류 모델.\n\n성과: 페이로드 복호화 없이 15개 앱 카테고리를 95.2% 정확도로 분류하여 제로 트러스트 보안 아키텍처 내 트래픽 정책 자동화에 기여.",
    tech: ["Python", "PyTorch", "Scapy", "Scikit-Learn"],
    tags: ["Cybersecurity", "Deep Learning"],
    status: "EXECUTED",
    accuracy: "95.2%",
  },
  {
    id: "QD-011",
    field: "ENERGY",
    title: "Battery Degradation Forecast",
    titleKr: "ESS 배터리 수명 열화 예측",
    description: "참여자: 손예진, 송다인, 송민규\n\n프로젝트 목표: 에너지 저장 시스템(ESS)의 충방전 사이클 데이터와 셀 온도 로그를 분석하여 잔존 용량(SOH)을 예측하고 교체 시점을 사전 알림.\n\n성과: 1,000사이클 이후 SOH 예측 오차를 MAPE 2.8% 이내로 제어하여 ESS 운영 비용 최적화 도구로 현장 시범 배포.",
    tech: ["Python", "LSTM", "TensorFlow", "InfluxDB"],
    tags: ["Energy", "Predictive Maintenance"],
    status: "EXECUTED",
    accuracy: "97.2%",
  },
  {
    id: "QD-012",
    field: "LEGAL",
    title: "Contract Clause Risk Scorer",
    titleKr: "계약서 조항 위험도 자동 평가",
    description: "참여자: 송유진, 신도윤, 신수빈, 신윤재\n\n프로젝트 목표: 기업 간 계약서 PDF를 OCR 처리한 뒤, 불리한 조항(위약금, 면책, 자동갱신 등)을 자동 탐지하여 위험 등급을 매기는 NLP 파이프라인.\n\n성과: 법률 도메인 특화 BERT 모델을 파인튜닝하여 조항별 위험 등급 분류 정확도 86.5%를 달성, 법무팀 계약 검토 시간을 40% 단축.",
    tech: ["Python", "HuggingFace", "Tesseract", "FastAPI"],
    tags: ["LegalTech", "NLP"],
    status: "EXECUTED",
    accuracy: "86.5%",
  },
  {
    id: "QD-013",
    field: "FOOD",
    title: "Food Waste Volume Estimator",
    titleKr: "급식 잔반량 영상 인식 시스템",
    description: "참여자: 양서현, 양하은, 오승아\n\n프로젝트 목표: 학교·기업 급식소의 퇴식구에 설치된 카메라 영상으로 잔반 부피를 자동 추정하여 식단 개선 및 발주량 조절에 활용.\n\n성과: 3D 깊이 카메라와 세그멘테이션 모델을 결합하여 잔반량 추정 오차 ±8% 이내를 달성, 시범 운영 학교에서 식재료 폐기량 22% 감소.",
    tech: ["Python", "YOLOv8", "OpenCV", "RealSense SDK"],
    tags: ["FoodTech", "Computer Vision"],
    status: "EXECUTED",
    accuracy: "92.0%",
  },
  {
    id: "QD-014",
    field: "MARITIME",
    title: "Port Congestion Early Warning",
    titleKr: "항만 체선 조기 경보 시스템",
    description: "참여자: 오지안, 원서영, 유예원\n\n프로젝트 목표: 전 세계 AIS 선박 위치 데이터와 항만 CY 재고율, 기상 예보를 결합하여 주요 항만의 체선 위험을 72시간 전에 예측.\n\n성과: 부산항·인천항 대상 시뮬레이션에서 체선 위험 경보 정확도 84.7%를 기록하여 선사 배선 스케줄 조정 지원 도구로 제안.",
    tech: ["Python", "GeoPandas", "Prophet", "Plotly"],
    tags: ["Maritime", "TimeSeries"],
    status: "EXECUTED",
    accuracy: "84.7%",
  },
  {
    id: "QD-015",
    field: "SPACE",
    title: "Satellite Debris Collision Prob.",
    titleKr: "우주 파편 충돌 확률 산출 모델",
    description: "참여자: 유태빈, 윤도현, 윤서아\n\n프로젝트 목표: TLE(Two-Line Element) 궤도 데이터를 기반으로 저궤도 위성과 우주 파편 간의 근접 조우 이벤트를 시뮬레이션하고 충돌 확률 산출.\n\n성과: 궤도 전파 오차를 보정하는 앙상블 기법을 적용하여 기존 단일 모델 대비 충돌 경고 정밀도를 35% 향상.",
    tech: ["Python", "Astropy", "NumPy", "Plotly"],
    tags: ["Space", "Simulation"],
    status: "ARCHIVED",
    accuracy: "—",
  },
  {
    id: "QD-016",
    field: "FASHION",
    title: "Trend Color Palette Forecaster",
    titleKr: "패션 트렌드 컬러 팔레트 예측",
    description: "참여자: 윤시후, 윤지호, 이가현, 이도엽\n\n프로젝트 목표: 글로벌 패션위크 런웨이 이미지와 SNS 해시태그 트렌드를 분석하여 다음 시즌 유행 컬러 팔레트를 자동 예측.\n\n성과: HSV 색공간 클러스터링과 시계열 추이 분석을 결합하여 주요 컬러 5개 중 4개를 정확히 예측(적중률 80%), 패션 MD 기획 자료로 활용.",
    tech: ["Python", "OpenCV", "K-Means", "Scrapy"],
    tags: ["Fashion", "Clustering"],
    status: "EXECUTED",
    accuracy: "80.0%",
  },
  {
    id: "QD-017",
    field: "MUSIC",
    title: "Stem Separation Quality Scorer",
    titleKr: "음원 스템 분리 품질 자동 평가",
    description: "참여자: 이서윤, 이수현, 이시은\n\n프로젝트 목표: AI 기반 음원 분리(보컬, 드럼, 베이스, 기타) 결과물의 품질을 SDR/SIR 지표 외에 청각적 자연스러움까지 평가하는 메트릭 모델.\n\n성과: 전문 엔지니어의 주관 평가 점수와 0.87 상관관계를 달성하여 음원 분리 알고리즘 자동 벤치마크 시스템에 탑재.",
    tech: ["Python", "Librosa", "PyTorch", "Demucs"],
    tags: ["Audio", "Quality Assessment"],
    status: "EXECUTED",
    accuracy: "87.0%",
  },
  {
    id: "QD-018",
    field: "GAMING",
    title: "In-Game Economy Balancer",
    titleKr: "게임 내 경제 시스템 밸런싱 분석",
    description: "참여자: 이유담, 이주하, 이채린, 이한결\n\n프로젝트 목표: MMORPG 게임 내 재화 유통량, 아이템 거래 가격, 유저 보유 자산 분포를 시계열 분석하여 인플레이션 위험 구간을 조기 탐지.\n\n성과: 게임 경제 지표 이상치를 평균 48시간 전에 경보하는 모니터링 대시보드를 구축하여 운영팀의 선제적 개입 가능.",
    tech: ["Python", "Pandas", "Plotly", "Redis"],
    tags: ["Gaming", "Anomaly Detection"],
    status: "EXECUTED",
    accuracy: "85.6%",
  },
  {
    id: "QD-019",
    field: "REAL_ESTATE",
    title: "Noise Pollution Price Impact",
    titleKr: "소음 공해가 주택 가격에 미치는 영향 분석",
    description: "참여자: 이현아, 임수인, 장예은\n\n프로젝트 목표: 교통 소음 지도(소음 등고선)와 실거래가 데이터를 공간 조인하여 데시벨 수준에 따른 아파트 가격 감소 효과를 헤도닉 모형으로 정량화.\n\n성과: 1dB 증가 시 평균 0.38% 가격 하락 효과를 통계적으로 유의하게 도출, 도시 계획 정책 보고서에 인용.",
    tech: ["Python", "Statsmodels", "GeoPandas", "Matplotlib"],
    tags: ["Real Estate", "Spatial Econometrics"],
    status: "EXECUTED",
    accuracy: "82.4%",
  },
  {
    id: "QD-020",
    field: "INSURANCE",
    title: "Flood Damage Claim Estimator",
    titleKr: "수해 피해 보험금 자동 산정 시스템",
    description: "참여자: 장유하, 전도하, 전서연, 정가인\n\n프로젝트 목표: 침수 피해 현장 드론 촬영 이미지와 건물 정보 DB를 매칭하여 피해 등급을 분류하고 예상 보험금을 자동 산출.\n\n성과: 피해 등급 분류 정확도 89.1%와 보험금 추정 오차 ±12% 이내를 동시에 달성하여 현장 조사원 초기 평가 보조 도구로 배포.",
    tech: ["Python", "YOLOv8", "XGBoost", "FastAPI"],
    tags: ["Insurance", "Computer Vision"],
    status: "EXECUTED",
    accuracy: "89.1%",
  },
  {
    id: "QD-021",
    field: "TELECOM",
    title: "5G Cell Tower Placement AI",
    titleKr: "5G 기지국 최적 배치 AI 모델",
    description: "참여자: 정다윤, 정세윤, 정은호\n\n프로젝트 목표: 인구 밀도, 건물 높이, 기존 기지국 커버리지 데이터를 입력으로 신규 5G 기지국의 최적 좌표를 산출하는 공간 최적화 모델.\n\n성과: 유전 알고리즘 기반 최적화를 통해 동일 기지국 수 대비 커버리지 면적을 14.2% 확대하는 배치안을 도출.",
    tech: ["Python", "DEAP", "GeoPandas", "Plotly"],
    tags: ["Telecom", "Optimization"],
    status: "IN_PROGRESS",
    accuracy: "—",
  },
  {
    id: "QD-022",
    field: "CONSTRUCTION",
    title: "Concrete Crack Severity Grader",
    titleKr: "콘크리트 균열 심각도 자동 등급 분류",
    description: "참여자: 정지환, 정하윤, 조민찬, 조서아\n\n프로젝트 목표: 구조물 표면 촬영 이미지에서 균열을 검출하고 폭·길이·분기 패턴에 따라 5단계 심각도를 자동 판정하는 CV 모델.\n\n성과: 구조 안전 전문가의 현장 판정과 93.1% 일치율을 기록하여 정기 안전 점검 보조 시스템으로 시범 운영.",
    tech: ["Python", "PyTorch", "Segment-Anything", "OpenCV"],
    tags: ["Construction", "Defect Detection"],
    status: "EXECUTED",
    accuracy: "93.1%",
  },
  {
    id: "QD-023",
    field: "PHARMA",
    title: "Drug Interaction Graph Predictor",
    titleKr: "약물 상호작용 그래프 기반 예측",
    description: "참여자: 조아인, 조원빈, 주하린\n\n프로젝트 목표: FDA 약물 데이터베이스의 분자 구조·약리 특성 그래프와 기존 부작용 보고 데이터를 학습하여 미지의 약물 조합 부작용을 예측.\n\n성과: AUROC 0.91을 달성하여 병원 약제부의 처방 검토 시 2차 경보 시스템 프로토타입으로 개발.",
    tech: ["Python", "DGL", "RDKit", "Scikit-Learn"],
    tags: ["Pharma", "Graph ML"],
    status: "EXECUTED",
    accuracy: "91.0%",
  },
  {
    id: "QD-024",
    field: "TOURISM",
    title: "Travel Demand Surge Predictor",
    titleKr: "여행 수요 급증 사전 예측 모델",
    description: "참여자: 차미르, 차유빈, 천소율\n\n프로젝트 목표: 항공권 검색량, SNS 여행 해시태그 추이, 환율 변동, 공휴일 캘린더를 종합하여 특정 여행지의 수요 급증 시점을 2주 전에 예측.\n\n성과: 주요 10개 여행지에 대해 수요 급증 이벤트 탐지 F1-Score 0.84를 기록하여 여행사 동적 가격 전략 수립에 기여.",
    tech: ["Python", "Prophet", "Scrapy", "Pandas"],
    tags: ["Tourism", "Demand Forecasting"],
    status: "EXECUTED",
    accuracy: "84.0%",
  },
  {
    id: "QD-025",
    field: "WASTE_MGMT",
    title: "Recycling Contamination Detector",
    titleKr: "재활용 오염물 혼입 자동 탐지",
    description: "참여자: 최가은, 최도운, 최서윤\n\n프로젝트 목표: 재활용 분류 컨베이어 벨트 위 CCTV 영상에서 오염된 재활용품(음식물 잔여, 비닐 혼입 등)을 실시간 탐지하여 분리 품질 향상.\n\n성과: 오염 탐지 정밀도 94.3%와 초당 15프레임 처리 속도를 동시에 달성하여 재활용 선별장 시범 배포.",
    tech: ["Python", "YOLOv8", "TensorRT", "OpenCV"],
    tags: ["Environment", "Object Detection"],
    status: "EXECUTED",
    accuracy: "94.3%",
  },
  {
    id: "QD-026",
    field: "DEFENSE",
    title: "Radar Signal Classification Net",
    titleKr: "레이더 신호 패턴 자동 분류 네트워크",
    description: "참여자: 최수연, 최아림, 최유담, 최지환\n\n프로젝트 목표: 다양한 레이더 펄스 반복 주기(PRI)와 주파수 호핑 패턴을 딥러닝 모델로 학습하여 방사체 유형을 자동 식별.\n\n성과: 12가지 방사체 유형에 대해 분류 정확도 96.7%를 기록, 기존 수동 분석 대비 처리 속도 100배 이상 향상.",
    tech: ["Python", "PyTorch", "SciPy", "NumPy"],
    tags: ["Defense", "Signal Processing"],
    status: "ARCHIVED",
    accuracy: "—",
  },
  {
    id: "QD-027",
    field: "LOGISTICS",
    title: "Last-Mile Route Reinforcement",
    titleKr: "라스트마일 배송 경로 강화학습 최적화",
    description: "참여자: 한소미, 한예솔, 홍시아\n\n프로젝트 목표: 다수의 배송 건을 동시에 처리하는 라이더의 최적 경로를 강화학습 기반으로 실시간 생성하여 총 이동 거리와 시간을 최소화.\n\n성과: OR-Tools 휴리스틱 대비 평균 배송 시간을 11.3% 단축하고, 실시간 교통 상황 반영으로 지연 배송률 8% 감소.",
    tech: ["Python", "Stable-Baselines3", "OSMnx", "FastAPI"],
    tags: ["Logistics", "Reinforcement Learning"],
    status: "EXECUTED",
    accuracy: "88.7%",
  },
  {
    id: "QD-028",
    field: "MINING",
    title: "Ore Grade Prediction from Drill",
    titleKr: "시추 데이터 기반 광석 품위 예측",
    description: "참여자: 황가온, 황도연, 황서우\n\n프로젝트 목표: 시추 코어 샘플의 지구화학 분석 데이터와 3D 지질 모델을 결합하여 미탐사 구역의 광석 품위를 공간 보간 예측.\n\n성과: 크리깅(Kriging)과 그래디언트 부스팅을 융합한 하이브리드 모델로 교차 검증 R² 0.88을 달성하여 채굴 계획 수립에 활용.",
    tech: ["Python", "PyKrige", "LightGBM", "Plotly"],
    tags: ["Mining", "Geostatistics"],
    status: "EXECUTED",
    accuracy: "88.0%",
  },
  {
    id: "QD-029",
    field: "FINTECH",
    title: "Alt-Data Credit Scoring Model",
    titleKr: "대안 데이터 기반 신용 평가 모델",
    description: "참여자: 허윤아, 진시윤, 공서연\n\n프로젝트 목표: 기존 금융 이력이 없는 씬파일러(Thin-filer)를 위해 통신요금 납부, 공과금 이력, 소셜 활동 데이터를 활용한 대안 신용 평가 모델.\n\n성과: 기존 CB 스코어 미보유자 대상 디폴트 예측 KS 통계량 0.42를 기록하여 금융 포용성 확대 정책 연구 자료로 인용.",
    tech: ["Python", "CatBoost", "SHAP", "Pandas"],
    tags: ["FinTech", "Credit Scoring"],
    status: "EXECUTED",
    accuracy: "83.9%",
  },
  {
    id: "QD-030",
    field: "MOBILITY",
    title: "Shared Scooter Rebalancing AI",
    titleKr: "공유 킥보드 재배치 최적화 AI",
    description: "참여자: 탁하윤, 구예진, 김가온\n\n프로젝트 목표: 시간대별 공유 킥보드 수요-공급 불균형 데이터를 분석하여 야간 재배치 트럭의 최적 수거·배포 계획을 자동 생성.\n\n성과: 오전 출근 시간대 킥보드 가용률을 기존 대비 28% 향상시키면서 재배치 트럭 운행 거리를 15% 감소.",
    tech: ["Python", "PuLP", "GeoPandas", "Streamlit"],
    tags: ["Mobility", "Optimization"],
    status: "EXECUTED",
    accuracy: "90.2%",
  },
  {
    id: "QD-031",
    field: "BIOMEDICAL",
    title: "ECG Arrhythmia Multi-Label",
    titleKr: "심전도 다중 부정맥 분류 모델",
    description: "참여자: 강서윤, 김민서, 박서진\n\n프로젝트 목표: 12유도 심전도(ECG) 원시 신호에서 10가지 부정맥 유형을 동시에 탐지하는 다중 레이블 분류 CNN-LSTM 모델.\n\n성과: PhysioNet 챌린지 기준 Macro F1-Score 0.89를 달성하여 웨어러블 심박 모니터 탑재 가능성 검토.",
    tech: ["Python", "PyTorch", "WFDB", "NumPy"],
    tags: ["Healthcare", "Signal Processing"],
    status: "EXECUTED",
    accuracy: "89.0%",
  },
  {
    id: "QD-032",
    field: "CLIMATE",
    title: "Wildfire Spread Simulator",
    titleKr: "산불 확산 시뮬레이션 예측 모델",
    description: "참여자: 김지안, 류다온, 서예림\n\n프로젝트 목표: 지형(DEM), 식생 분포, 풍속·풍향 예보 데이터를 입력으로 산불 발생 시 6시간 단위 확산 면적과 방향을 시뮬레이션.\n\n성과: 과거 산불 사례 30건에 대한 역검증에서 확산 면적 오차 ±18% 이내를 달성하여 산림청 대응 훈련 시나리오 생성에 활용.",
    tech: ["Python", "NumPy", "Rasterio", "Matplotlib"],
    tags: ["Climate", "Simulation"],
    status: "IN_PROGRESS",
    accuracy: "—",
  },
  {
    id: "QD-033",
    field: "SOCIAL",
    title: "Hate Speech Severity Gradation",
    titleKr: "온라인 혐오 발언 심각도 등급 분류",
    description: "참여자: 손예진, 양하은, 이서윤\n\n프로젝트 목표: 단순 부정 표현과 심각한 혐오 발언을 5단계 등급으로 세분화하여 플랫폼 자동 조치 기준을 정교화하는 NLP 모델.\n\n성과: 기존 이진 분류 시스템 대비 과잉 차단율을 40% 줄이면서 심각 등급 탐지 Recall을 92.1%로 유지.",
    tech: ["Python", "KoELECTRA", "HuggingFace", "FastAPI"],
    tags: ["NLP", "Content Moderation"],
    status: "EXECUTED",
    accuracy: "92.1%",
  },
  {
    id: "QD-034",
    field: "AGRITECH",
    title: "Livestock Health Sound Monitor",
    titleKr: "축사 가축 건강 상태 음향 모니터링",
    description: "참여자: 신도윤, 오승아, 전서연\n\n프로젝트 목표: 축사 내부 마이크로 수집된 소의 기침, 호흡음, 반추 소리 패턴을 분석하여 호흡기 질환을 증상 발현 전에 조기 감지.\n\n성과: 호흡기 이상 징후를 증상 발현 평균 36시간 전에 탐지하는 데 성공하여 수의학적 조기 개입 시스템으로 특허 출원 준비.",
    tech: ["Python", "Librosa", "TensorFlow", "RaspberryPi"],
    tags: ["AgriTech", "Audio ML"],
    status: "EXECUTED",
    accuracy: "88.5%",
  },
  {
    id: "QD-035",
    field: "EDTECH",
    title: "Lecture Engagement Heatmap",
    titleKr: "강의 집중도 시간대별 히트맵 분석",
    description: "참여자: 정다윤, 조민찬, 허윤아\n\n프로젝트 목표: 온라인 강의 영상의 시청 로그(일시정지, 되감기, 배속 변경)를 분석하여 학습자들이 어려워하거나 지루해하는 구간을 자동 식별.\n\n성과: 구간별 집중도 지수를 시각화하여 강사에게 콘텐츠 개선 포인트를 제시, 시범 적용 강의의 완강률 19% 향상.",
    tech: ["Python", "Pandas", "D3.js", "Flask"],
    tags: ["EdTech", "Analytics"],
    status: "EXECUTED",
    accuracy: "85.3%",
  },
  {
    id: "QD-036",
    field: "FOOD",
    title: "Recipe Nutrition Auto-Estimator",
    titleKr: "레시피 텍스트 기반 영양 성분 자동 추정",
    description: "참여자: 최서윤, 황가온, 김채원\n\n프로젝트 목표: 자연어로 작성된 요리 레시피 텍스트에서 재료와 분량을 추출하고 식품 영양 DB와 매칭하여 1인분 영양 성분을 자동 계산.\n\n성과: 주요 영양소(칼로리, 탄수화물, 단백질, 지방) 추정 오차를 ±10% 이내로 제어하여 건강 관리 앱 API로 서비스화.",
    tech: ["Python", "SpaCy", "FastAPI", "PostgreSQL"],
    tags: ["FoodTech", "NER"],
    status: "EXECUTED",
    accuracy: "90.0%",
  },
  {
    id: "QD-037",
    field: "ENERGY",
    title: "Solar Panel Defect Thermal Map",
    titleKr: "태양광 패널 열화상 결함 탐지",
    description: "참여자: 박유빈, 윤도현, 이채린\n\n프로젝트 목표: 드론으로 촬영한 태양광 발전소의 열화상(IR) 이미지에서 핫스팟, 셀 크랙, PID 결함을 자동 탐지·분류.\n\n성과: 25MW 규모 발전소 전수 조사를 3일에서 4시간으로 단축하면서 결함 탐지율 96.8% 달성.",
    tech: ["Python", "PyTorch", "OpenCV", "GeoPandas"],
    tags: ["Renewable Energy", "Thermal Imaging"],
    status: "EXECUTED",
    accuracy: "96.8%",
  },
  {
    id: "QD-038",
    field: "LEGAL",
    title: "Case Outcome Probability Engine",
    titleKr: "민사 소송 판결 결과 확률 예측 엔진",
    description: "참여자: 배소은, 정은호, 장유하\n\n프로젝트 목표: 법원 공개 판결문 코퍼스에서 사건 유형, 청구 금액, 법적 쟁점 키워드를 추출하여 원고 승소 확률을 예측하는 분류 모델.\n\n성과: 손해배상 소송 카테고리에서 판결 방향 예측 정확도 78.3%를 달성, 법률 상담 초기 단계의 참고 자료로 활용 가능성 제시.",
    tech: ["Python", "HuggingFace", "Scikit-Learn", "Pandas"],
    tags: ["LegalTech", "Classification"],
    status: "EXECUTED",
    accuracy: "78.3%",
  },
  {
    id: "QD-039",
    field: "SECURITY",
    title: "Deepfake Voice Detection System",
    titleKr: "딥페이크 음성 탐지 시스템",
    description: "참여자: 서지원, 이가현, 장예은\n\n프로젝트 목표: AI 합성 음성과 실제 음성을 스펙트로그램 특성 차이로 구별하여 보이스 피싱 및 신원 사칭을 실시간 탐지.\n\n성과: 최신 TTS 엔진으로 생성된 합성 음성에 대해 탐지 정확도 94.6%를 기록하며, 콜센터 인바운드 실시간 검증 시스템에 연동.",
    tech: ["Python", "Librosa", "PyTorch", "FastAPI"],
    tags: ["Security", "Audio Forensics"],
    status: "EXECUTED",
    accuracy: "94.6%",
  },
  {
    id: "QD-040",
    field: "RETAIL",
    title: "Shelf Space Revenue Maximizer",
    titleKr: "매대 공간 수익 극대화 배치 최적화",
    description: "참여자: 전도하, 최도운, 홍시아\n\n프로젝트 목표: 편의점·마트 매대의 SKU별 진열 위치와 매출 데이터를 분석하여 공간 단위 수익을 극대화하는 최적 배치안을 산출.\n\n성과: 혼합 정수 프로그래밍(MIP) 기반 최적화를 통해 동일 매대 면적 대비 매출을 시뮬레이션상 9.4% 증가시키는 배치안 도출.",
    tech: ["Python", "PuLP", "Pandas", "Plotly"],
    tags: ["Retail", "Optimization"],
    status: "EXECUTED",
    accuracy: "89.4%",
  },
  {
    id: "QD-041",
    field: "TELECOM",
    title: "Network Anomaly Root Cause AI",
    titleKr: "통신 네트워크 장애 원인 자동 추론",
    description: "참여자: 김연우, 박가영, 신수빈\n\n프로젝트 목표: 기지국 KPI 로그의 다차원 시계열 이상 패턴에서 장애 근본 원인(Root Cause)을 인과 추론 기법으로 자동 식별.\n\n성과: Granger 인과성 및 구조 방정식 모형을 결합하여 장애 원인 top-3 추천 적중률 87.2% 달성, 평균 복구 시간(MTTR) 22% 단축.",
    tech: ["Python", "CausalNex", "Pandas", "Grafana"],
    tags: ["Telecom", "Causal Inference"],
    status: "EXECUTED",
    accuracy: "87.2%",
  },
  {
    id: "QD-042",
    field: "CONSTRUCTION",
    title: "BIM Clash Detection Automator",
    titleKr: "BIM 설계 간섭 자동 탐지 시스템",
    description: "참여자: 송다인, 윤서아, 정하윤\n\n프로젝트 목표: 건축 BIM(Building Information Model) IFC 파일에서 배관, 전선관, 구조체 간 물리적 간섭(Clash)을 자동 탐지하고 우선순위를 매기는 분석 도구.\n\n성과: 수작업 검토 대비 간섭 탐지 커버리지를 98.5%로 향상시키고 검토 소요 시간을 80% 단축.",
    tech: ["Python", "IfcOpenShell", "NumPy", "Plotly"],
    tags: ["Construction", "BIM"],
    status: "IN_PROGRESS",
    accuracy: "—",
  },
  {
    id: "QD-043",
    field: "PHARMA",
    title: "Clinical Trial Patient Matching",
    titleKr: "임상시험 환자 매칭 추천 시스템",
    description: "참여자: 김수아, 박다율, 이도엽\n\n프로젝트 목표: 전자의무기록(EMR) 텍스트에서 환자 특성을 추출하고, 진행 중인 임상시험의 참여 기준과 자동 매칭하여 적격 환자를 추천.\n\n성과: 수작업 스크리닝 대비 적격 환자 발굴률을 3.2배 향상시키면서 위양성률을 7% 미만으로 유지.",
    tech: ["Python", "SpaCy", "SBERT", "Elasticsearch"],
    tags: ["Pharma", "NLP"],
    status: "EXECUTED",
    accuracy: "90.8%",
  },
  {
    id: "QD-044",
    field: "TOURISM",
    title: "Cultural Heritage AR Guide Data",
    titleKr: "문화재 AR 가이드 데이터 파이프라인",
    description: "참여자: 나윤서, 박지윤, 오지안\n\n프로젝트 목표: 국보·보물급 문화재의 3D 스캔 포인트 클라우드와 역사 해설 텍스트를 결합하여 AR 관광 가이드 앱의 백엔드 데이터 파이프라인 구축.\n\n성과: 50개 문화재에 대해 3D 정합 정확도 2mm 이내, 해설 텍스트 자동 요약 ROUGE-L 0.52를 달성.",
    tech: ["Python", "Open3D", "HuggingFace", "FastAPI"],
    tags: ["Tourism", "3D Processing"],
    status: "ARCHIVED",
    accuracy: "—",
  },
  {
    id: "QD-045",
    field: "WASTE_MGMT",
    title: "Illegal Dumping Hotspot Predictor",
    titleKr: "불법 투기 다발 지역 예측 모델",
    description: "참여자: 김하람, 문정우, 원서영\n\n프로젝트 목표: CCTV 적발 이력, 야간 조명도, 인구 밀도, 도로 유형 데이터를 공간 분석하여 불법 투기 발생 확률이 높은 취약 지점을 사전 예측.\n\n성과: 과거 2년간 적발 데이터로 학습한 모델이 신규 불법 투기 지점의 76%를 상위 예측 구역 안에서 포착, 단속 효율 향상에 기여.",
    tech: ["Python", "XGBoost", "GeoPandas", "Folium"],
    tags: ["Environment", "Spatial ML"],
    status: "EXECUTED",
    accuracy: "85.0%",
  },
  {
    id: "QD-046",
    field: "MEDIA",
    title: "Article Headline A/B Auto-Gen",
    titleKr: "뉴스 기사 헤드라인 자동 생성 A/B 시스템",
    description: "참여자: 이현아, 최가은, 황도연\n\n프로젝트 목표: 뉴스 기사 본문을 입력으로 클릭률이 높을 것으로 예상되는 헤드라인 후보 3개를 자동 생성하고 CTR 예측 모델로 순위를 매기는 파이프라인.\n\n성과: 실제 편집자가 작성한 헤드라인 대비 CTR 예측 모델 기준 평균 12.8% 높은 클릭률을 기록하는 헤드라인 생성에 성공.",
    tech: ["Python", "GPT-API", "Scikit-Learn", "FastAPI"],
    tags: ["Media", "Generative AI"],
    status: "EXECUTED",
    accuracy: "82.8%",
  },
  {
    id: "QD-047",
    field: "GAMING",
    title: "Player Toxicity Scoring Engine",
    titleKr: "게임 유저 독성 행동 스코어링 엔진",
    description: "참여자: 임수인, 정지환, 박은서, 조서아\n\n프로젝트 목표: 게임 내 채팅 로그, 신고 이력, 게임 플레이 패턴(고의 탈주, 팀킬 등)을 종합 분석하여 유저별 독성 점수를 산출하고 단계별 제재 기준 자동화.\n\n성과: 독성 유저 조기 탐지 Precision 91.5%를 달성하여 커뮤니티 건전성 지표가 시범 적용 3개월간 17% 개선.",
    tech: ["Python", "KoBERT", "XGBoost", "Redis"],
    tags: ["Gaming", "NLP"],
    status: "EXECUTED",
    accuracy: "91.5%",
  },
  {
    id: "QD-048",
    field: "BEGINNER",
    title: "Titanic Survival Classifier",
    titleKr: "타이타닉 생존자 분류 입문 프로젝트",
    description: "참여자: 이가온, 김도은, 박지수\n\n프로젝트 목표: Kaggle의 대표 입문 데이터셋인 Titanic 데이터를 활용하여 성별, 나이, 객실 등급 등 변수를 분석하고 로지스틱 회귀 및 의사결정나무로 생존 여부를 예측.\n\n성과: 전처리(결측치 처리, 범주형 인코딩)와 교차 검증을 직접 구현하여 테스트셋 기준 정확도 79.4%를 달성. 팀원 전원이 EDA부터 모델 제출까지 전 과정을 독립적으로 경험.",
    tech: ["Python", "Pandas", "Scikit-Learn", "Matplotlib"],
    tags: ["Beginner", "Classification"],
    status: "EXECUTED",
    accuracy: "79.4%",
  },
  {
    id: "QD-049",
    field: "BEGINNER",
    title: "Boston Housing Price Regression",
    titleKr: "보스턴 주택 가격 선형 회귀 분석",
    description: "참여자: 최예린, 강민준, 한지호, 오다은\n\n프로젝트 목표: 보스턴 주택 데이터셋의 13개 변수(범죄율, 방 수, 접근성 등)와 주택 중위 가격 간의 관계를 탐색적으로 분석하고, 단순/다중 선형 회귀 모델을 직접 구현.\n\n성과: 변수 간 다중공선성 확인 및 Ridge 정규화 적용을 통해 RMSE를 기본 모델 대비 18% 줄이며 회귀 분석의 핵심 개념을 체득.",
    tech: ["Python", "Pandas", "Scikit-Learn", "Seaborn"],
    tags: ["Beginner", "Regression"],
    status: "EXECUTED",
    accuracy: "81.6%",
  },
  {
    id: "QD-050",
    field: "BEGINNER",
    title: "Iris Species KNN Classifier",
    titleKr: "붓꽃 품종 K-최근접 이웃 분류",
    description: "참여자: 류채은, 노서준, 임하은\n\n프로젝트 목표: 머신러닝 입문의 'Hello World'로 불리는 Iris 데이터셋으로 꽃잎/꽃받침의 길이·너비 4개 특성을 이용해 KNN 알고리즘으로 3종 품종을 분류.\n\n성과: K값 튜닝 실험(K=1~20)과 결정 경계 시각화를 통해 최적 K=7에서 정확도 96.7%를 기록. 하이퍼파라미터의 중요성을 직접 비교 실험으로 체득.",
    tech: ["Python", "Scikit-Learn", "Matplotlib", "NumPy"],
    tags: ["Beginner", "Classification"],
    status: "EXECUTED",
    accuracy: "96.7%",
  },
  {
    id: "QD-051",
    field: "BEGINNER",
    title: "Movie Review Sentiment Analysis",
    titleKr: "영화 리뷰 긍부정 감성 분류 입문",
    description: "참여자: 고은서, 이준혁, 백다은, 엄지호\n\n프로젝트 목표: 네이버 영화 리뷰 데이터(NSMC)를 크롤링하여 TF-IDF 벡터화 및 나이브 베이즈 분류기로 리뷰의 긍·부정 감성을 예측하는 NLP 입문 파이프라인 구현.\n\n성과: 불용어 처리·형태소 분석(KoNLPy)을 적용하여 Accuracy 84.2%를 달성. 텍스트 데이터의 전처리부터 벡터화, 모델 적용까지의 NLP 기본 흐름을 팀원 모두 직접 경험.",
    tech: ["Python", "KoNLPy", "Scikit-Learn", "Pandas"],
    tags: ["Beginner", "NLP"],
    status: "EXECUTED",
    accuracy: "84.2%",
  },
  {
    id: "QD-052",
    field: "BEGINNER",
    title: "Customer Segmentation via K-Means",
    titleKr: "K-평균 군집화 기반 고객 세분화",
    description: "참여자: 신아름, 홍준서, 구민서, 안채원\n\n프로젝트 목표: 온라인 쇼핑몰의 구매 금액·빈도·최근성(RFM) 데이터를 활용하여 K-Means 군집화로 고객을 4개 세그먼트로 분류하고 각 집단의 특성을 시각화.\n\n성과: 엘보우 기법으로 최적 군집 수(K=4)를 결정하고 각 세그먼트(VIP, 일반, 휴면, 신규)별 마케팅 전략 제안서를 작성하여 비즈니스 분석의 실질적인 활용법 체득.",
    tech: ["Python", "Scikit-Learn", "Pandas", "Plotly"],
    tags: ["Beginner", "Clustering"],
    status: "EXECUTED",
    accuracy: "—",
  }
];

// =============================================================================
// Curriculum Steps
// =============================================================================

export const curriculumSteps = [
  {
    step: 1,
    title: "1) 방학 집중 학습(기초 학습)",
    description: "• 주 1회 정기 모임 진행!\n• Python과 Pandas를 통한 데이터 조작과 시각화 및 예제 연습!\n• 이론과 실무를 동시에 다루며 실무에 필요한 이론 위주의 학습!\n• 참고: 포폴 제작 바로 희망하시는 분들은 바로 포폴용 프로젝트 진행하실 수 있습니다!"
  },
  {
    step: 2,
    title: "2) 학기 중 프로젝트",
    description: "• 격주 1회 정기 모임 진행!(학기 중 시험기간에는 유동적으로 진행됩니다)\n• kaagle 등의 머신러닝 예제 학습\n• 크롤링을 통한 데이터셋 확보 및 EDA 학습\n• 수준별 학습과 멘토링"
  }
];

// =============================================================================
// External Links
// =============================================================================

export const links = {
  applyForm: "https://tally.so/r/Pd40EB",
};
